name: Tests
on:
  push:
    branches: "*"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --system --dev

    - name: Run tests
      run: pytest tests.py
      env:
        TELEGRAM_TOKEN: "000000000:this-is-a-fake-token-from-trelegram"
        TRANSIFEX_TOKEN: ""
        DATABASE: "localhost"


    - name: Run linter
      run: black --check i17obot

